name: "debug_train"
dump_dir: "results_train/${.name}"
steps: 1_000
probe_freq: null
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: no_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 512
  n_layers: 8
  n_heads: 8

data:
  root_dir: /mnt/vast/pretraining-data-jsonl/
  sources:
    english/dclm_crossdeduped/shard_000: 100.0
  batch_size: 4
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: tokenizers/llama3/tokenizer.model

checkpoint:
  dump:
    every: 10000
    keep: 0
  eval:
    every: 10000
    keep: 0

logging:
  freq: 1